const CACHE='personal-loan-v3';
const ASSETS=['./','index.html','manifest.webmanifest','icon.svg'];
const FIX_STYLE=`<style id="iphone-layout-fix">
html,body{min-height:100%;scroll-behavior:auto!important;overscroll-behavior:none}
body{padding-top:0!important;padding-bottom:env(safe-area-inset-bottom)!important}
.app{padding-top:calc(18px + env(safe-area-inset-top))!important}
.lock{padding-top:calc(24px + env(safe-area-inset-top))!important;padding-bottom:calc(24px + env(safe-area-inset-bottom))!important}
</style>`;
const FIX_SCRIPT=`<script id="iphone-layout-fix-script">(function(){try{if('scrollRestoration' in history)history.scrollRestoration='manual';const resetTop=()=>{try{if(document.activeElement&&document.activeElement!==document.body)document.activeElement.blur()}catch(e){}window.scrollTo(0,0);document.documentElement.scrollTop=0;document.body.scrollTop=0};window.addEventListener('pageshow',()=>requestAnimationFrame(resetTop));window.addEventListener('load',()=>requestAnimationFrame(resetTop));document.addEventListener('visibilitychange',()=>{if(!document.hidden)setTimeout(resetTop,0)});const lock=document.getElementById('lockScreen');if(lock){new MutationObserver(()=>{if(getComputedStyle(lock).display==='none')requestAnimationFrame(resetTop)}).observe(lock,{attributes:true,attributeFilter:['style','class']})}setTimeout(resetTop,0)}catch(e){}})();<\/script>`;
async function fixedHtmlResponse(request){let response;try{response=await fetch(request,{cache:'no-store'})}catch(e){response=await caches.match(request)||await caches.match('./')}if(!response)return response;let text=await response.text();if(!text.includes('iphone-layout-fix'))text=text.replace('</head>',FIX_STYLE+'</head>').replace('</body>',FIX_SCRIPT+'</body>');return new Response(text,{status:response.status,statusText:response.statusText,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(ASSETS)))});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{await Promise.all((await caches.keys()).filter(k=>k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const clients=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const client of clients){try{await client.navigate(client.url)}catch(e){}}})())});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;const url=new URL(e.request.url);if(e.request.mode==='navigate'||url.pathname.endsWith('/mo-balance/')||url.pathname.endsWith('/mo-balance/index.html')){e.respondWith(fixedHtmlResponse(e.request));return}e.respondWith(fetch(e.request).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));return r}).catch(()=>caches.match(e.request)))});